#!/bin/sh

# BSD 2-Clause License
#
# Copyright (c) 2024-2026 Shi Yanling
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

EDITOR=${EDITOR:-vi}
export LC_ALL=C
unset LESS
cwd=$(pwd)
lmax=24

[ ! -e "$SFF_PIPE" ] && { echo "SFF_PIPE: no such file"; exit 0; }
sffpipe=$SFF_PIPE
sffdir=${sffpipe%/*}
tmpdir=${TMPDIR:-/tmp}
[ ! -w "$tmpdir" ] && tmpdir=$sffdir

exbuf1="${sffdir}/.exec-buf1"
exbuf2="${sffdir}/.exec-buf2"
lastop="${sffdir}/.last-operation"
cpbuf="${sffdir}/.buf-copy"
mvbuf="${sffdir}/.buf-move"
[ -e "$mvbuf" ] && cmbuf=$mvbuf || cmbuf=$cpbuf
tsel=$(mktemp -u "${tmpdir}/sff-tsel-XXXXXX")
tbuf1=$(mktemp -u "${tmpdir}/sff-tbuf1-XXXXXX")
tbuf2=$(mktemp -u "${tmpdir}/sff-tbuf2-XXXXXX")

# === sff extension functions ===

sffpipe_clear_sel()
{
	[ -p "$sffpipe" ] && printf "." >"$sffpipe"
}

sffpipe_refresh()
{
	[ "$1" = '-c' ] && _x='.' || _x=''
	[ -p "$sffpipe" ] && printf "*%s" "$_x" >"$sffpipe"
}

sffpipe_sel_file()
{
	[ -p "$sffpipe" ] && printf "@%s" "$1" >"$sffpipe"
}

sffpipe_enter_dir()
{
	[ -p "$sffpipe" ] && printf ">%s" "$1" >"$sffpipe"
}

sffpipe_get_sel()
{
	[ -p "$sffpipe" ] && printf "%s" "$$" >"$sffpipe" \
	|| { printf "\n%s: invalid FIFO file\n" "$sffpipe"; exit 1; }
}

sff_cleanup()
{
	_ecode=$?
	rm -f "$tsel" "$tbuf1" "$tbuf2" "$tlist"
	[ "$_ecode" -gt 0 ] && { printf "Press Enter to continue "; read -r _x; }
}
trap sff_cleanup EXIT HUP INT QUIT TERM

sff_init_bufs()
{
	[ -e "$exbuf1" ] && [ -e "$exbuf2" ] && [ -e "$lastop" ] && [ -e "$cmbuf" ] && return 0
	touch -a "$exbuf1" "$exbuf2" "$lastop" "$cmbuf"
	chmod 600 "$exbuf1" "$exbuf2" "$lastop" "$cmbuf"
	[ "$(id -u)" -eq 0 ] && chown $(ps -o uid= -p "$PPID") "$exbuf1" "$exbuf2" "$lastop" "$cmbuf"
}

sff_pwd_perm()
{
	[ ! -w "$cwd" ] && { printf "\n%s: Permission denied\n" "$cwd"; exit 1; }
}

sff_new()
{
	sff_pwd_perm
	sff_init_bufs
	tlist="${tmpdir}/sff-create-files-$(id -u)"
	: >"$tlist"

	while true; do
		LC_ALL= $EDITOR "$tlist"
		[ -e "$tlist" ] && sed -e 's|^/*||' -e 's|[ \t]*$||' -e '/^$/d' "$tlist" >"$tbuf1"
		[ ! -s "$tbuf1" ] && exit 0

		sed 's|/.*$||' "$tbuf1" | sort -u >"$tbuf2"
		_exf=$(tr '\n' '\0' <"$tbuf2" \
			| xargs -0 sh -c 'for f; do [ -e "$f" ] && printf "%s\n" "$f"; done' _ | head -n $lmax)
		if [ "$_exf" ]; then
			printf "\n%s\n... file(s) exist\n(b)ack / (c)ancel [b]: " "$_exf"; read -r _x
			case "$_x" in [cC]) exit 0;; *) continue;; esac
		fi
		break
	done

	_pwd=$(printf '%s' "$cwd" | tr '\n' '\035' | sed 's/[\|&]/\\&/g')
	sed "s|^|$_pwd/|" "$tbuf2" | tr '\n\035' '\0\n' >"$exbuf2"
	sed -e '/\//!d' -e 's|/[^/]*$||' -e "s|^|$_pwd/|" "$tbuf1" | sort -u | tr '\n' '\0' >"$exbuf1"
	printf "\n" >>"$exbuf1"
	sed -e '/\/$/d' -e "s|^|$_pwd/|" "$tbuf1" | tr '\n' '\0' >>"$exbuf1"
	sff_do_new
}

sff_do_new()
{
	printf "new" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr '\035' '\n')"

	printf "\nCreating...\n"
	tr '\0' '\n' <"$exbuf1" | sed '/^$/d'
	_err=0
	[ "$(head -c 1 "$exbuf1" | tr -d '\n')" ] \
	&& { head -n 1 "$exbuf1" | tr -d '\n' | tr '\035' '\n' | LC_ALL= xargs -0 mkdir -p || _err=1; }

	[ "$(tail -c 1 "$exbuf1" | tr -d '\n' | tr '\0' 'A')" ] \
	&& { tail -n +2 "$exbuf1" | tr '\035' '\n' | LC_ALL= xargs -0 touch || _err=1; }
	return $_err
}

sff_undo_new()
{
	[ ! -s "$exbuf2" ] && exit 0
	_op=$(cat "$lastop")
	printf "\nUndo %s? (y/n) [n]: " "$_op"; read -r _x
	case "$_x" in [yY]) :;; *) exit 0;; esac
	printf "un%s" "$_op" >"$lastop"
	sffpipe_refresh

	echo "Deleting..."
	LC_ALL= xargs -0 sh -c 'find "$@" -prune -cnewer "$0" -exec rm -rf {} +' "$exbuf2" <"$exbuf2"
}

sff_write_cbuf()
{
	sff_init_bufs
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" >"$cmbuf"
	case "$1" in
	'cp') [ -e "$mvbuf" ] && mv -f "$mvbuf" "$cpbuf";;
	'mv') [ -e "$cpbuf" ] && mv -f "$cpbuf" "$mvbuf";;
	esac
	sffpipe_clear_sel
}

sff_view_cbuf()
{
	if [ -s "$cmbuf" ]; then
		cat "$cmbuf"
		[ "$(find "$cmbuf" -mmin +30)" ] && _exp='[EXPIRED]' || _exp=''
		printf "%s: %s file(s) %s\n" "${cmbuf##*-}" $(wc -l <"$cmbuf") "$_exp"
	else
		echo "Buffer is empty"
	fi | LC_ALL= less -~ +G
}

sff_clear_cbuf()
{
	: >"$cmbuf"
}

sff_paste()
{
	[ ! -s "$cmbuf" ] || [ "$(find "$cmbuf" -mmin +30)" ] && exit 0
	sff_pwd_perm

	_pwd=$(printf "%s" "$cwd" | tr '\n' '\035' | sed 's/[\|&]/\\&/g')
	sed "G;s|$|$_pwd/|" "$cmbuf" | tr '\n\035' '\0\n' >"$exbuf1"

	_op=${cmbuf##*-}
	case "$_op" in
	'copy') sed "s|^.*/|$_pwd/|" "$cmbuf" | tr '\n\035' '\0\n' >"$exbuf2";;
	'move') sed "s|^.*/|$_pwd/|" "$cmbuf" | paste -d '\n' - "$cmbuf" | tr '\n\035' '\0\n' >"$exbuf2"
		touch -mt 202310011200 "$cmbuf";;
	esac
	sff_do_paste "$_op"
}

sff_do_paste()
{
	_cks=$(cksum "$exbuf1")
	case "$1" in
	'copy') _exf=$(xargs -0 sh -c 'for f; do [ -e "$f" ] && printf "%s\n" "$f"; done' _ <"$exbuf2" | head -n $lmax);;
	'move') _exf=$(tr '\n\0' '\035\n' <"$exbuf2" | sed 'n;d' | tr '\n\035' '\0\n' \
			| xargs -0 sh -c 'for f; do [ -e "$f" ] && printf "%s\n" "$f"; done' _ | head -n $lmax);;
	*) _exf='';;
	esac
	_x='o'
	if [ "$_exf" ]; then
		printf "\n%s\n... file(s) exist\n" "$_exf"
		printf "(s)kip all / (i)nteractive / (o)verwrite all / (c)ancel [c]: "; read -r _x
		case "$_x" in [sSiIoO]) :;; *) touch "$cmbuf"; exit 0;; esac
	fi
	[ "$_cks" != "$(cksum "$exbuf1")" ] && set -- 'null'
	printf "$1" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr '\035' '\n')"

	case "$1" in
	'copy') printf "\nCopying...\n"
		case "$_x" in
		[oO]) LC_ALL= xargs -0 -n 2 cp -afv <"$exbuf1";;
		[sS]) LC_ALL= xargs -0 -n 2 cp -anv <"$exbuf1";;
		[iI]) LC_ALL= xargs -0 -n 2 -o cp -aiv <"$exbuf1";;
		esac
		;;
	'move') printf "\nMoving...\n"
		case "$_x" in
		[oO]) LC_ALL= xargs -0 -n 2 mv -fv <"$exbuf1";;
		[sS]) LC_ALL= xargs -0 -n 2 mv -nv <"$exbuf1";;
		[iI]) LC_ALL= xargs -0 -n 2 -o mv -iv <"$exbuf1";;
		esac
		;;
	'null') echo "Aborted: operation expired"
		false;;
	esac
}

sff_rename()
{
	sff_init_bufs
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	sed 's|/[^/]*$||' "$tsel" >"$tbuf1"
	tlist="${tmpdir}/sff-rename-$(id -u)"
	if [ "$1" = 'p' ]; then
		cat "$tsel" >"$tlist"
	else
		sed 's|.*/||' "$tsel" >"$tlist"
	fi

	while true; do
		LC_ALL= $EDITOR "$tlist"
		sed -e 's|.*/||' -e 's|^[ \t]*$||' "$tlist" | paste -d '/' "$tsel" "$tbuf1" - \
		| sed -e '/^\(.*\)\1$/d' -e '/^/d' -e '/\/$/d' >"$tbuf2"
		[ ! -s "$tbuf2" ] && exit 0

		_dupn=$(cut -d '' -f 2 "$tbuf2" | sort | uniq -d | head -n $lmax)
		if [ "$_dupn" ]; then
			printf "\n%s\n... duplicate name(s)\n(b)ack / (c)ancel [b]: " "$_dupn"; read -r _x
			case "$_x" in [cC]) exit 0;; *) continue;; esac
		fi
		_exf=$(cut -d '' -f 2 "$tbuf2" | tr '\n\035' '\0\n' \
			| xargs -0 sh -c 'for f; do [ -e "$f" ] && printf "%s\n" "$f"; done' _ | head -n $lmax)
		if [ "$_exf" ]; then
			printf "\n%s\n... file(s) exist\n(b)ack / (c)ancel [b]: " "$_exf"; read -r _x
			case "$_x" in [cC]) exit 0;; *) continue;; esac
		fi
		break
	done

	tr '\036\n\035' '\0\0\n' <"$tbuf2" >"$exbuf1"
	sed 's/\(.*\)\(.*\)/\2\1/' "$tbuf2" | tr '\036\n\035' '\0\0\n' >"$exbuf2"
	sff_do_rename
}

sff_do_rename()
{
	printf "rename" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr '\035' '\n')"

	printf "\nRenaming...\n"
	LC_ALL= xargs -0 -n 2 mv -nv <"$exbuf1"
}

sff_undo_move()
{
	[ ! -s "$exbuf2" ] && exit 0
	_op=$(cat "$lastop")
	printf "\nUndo %s? (y/n) [n]: " "$_op"; read -r _x
	case "$_x" in [yY]) :;; *) exit 0;; esac
	printf "un%s" "$_op" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf1" | head -n 1 | tr '\035' '\n')"

	echo "Moving..."
	LC_ALL= xargs -0 -n 2 mv -n <"$exbuf2"
}

sff_duplicate()
{
	sff_init_bufs
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	printf "\nNumber of copies / (c)ancel [1]: "; read -r _x
	_x=$(printf "%s" "${_x:-'1'}" | tr -cd '0-9')
	_x=${_x#"${_x%%[!0]*}"}
	[ -z "$_x" ] && exit 0

	: >"$exbuf1"; : >"$exbuf2"
	while IFS= read -r _path; do
		_num=1
		_path=$(printf "%s" "$_path" | tr '\035' '\n')

		for _ in $(seq "$_x"); do
			_npath="${_path}_$_num"
			_i=$_num
			while [ -e "$_npath" ]; do
				_i=$((_i + 1))
				_npath="${_path}_$_i"
			done
			_num=$((_i + 1))

			printf "%s\0%s\0" "$_path" "$_npath" >>"$exbuf1"
			printf "%s\0" "$_npath" >>"$exbuf2"
		done
	done <"$tsel"
	sff_do_duplicate
}

sff_do_duplicate()
{
	printf "duplicate" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr '\035' '\n')"

	printf "\nDuplicating...\n"
	LC_ALL= xargs -0 -n 2 cp -av <"$exbuf1"
}

sff_delete()
{
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	_lines=$(wc -l <"$tsel")
	echo ""
	head -n $lmax "$tsel"
	[ "$_lines" -gt $lmax ] && echo "..."
	printf "Permanently delete %d file(s)? (y/n) [n]: " $_lines; read -r _x
	case "$_x" in [yY]) :;; *) exit 0;; esac
	sffpipe_refresh -c

	echo "Deleting..."
	tr '\n\035' '\0\n' <"$tsel" | LC_ALL= xargs -0 rm -rf
}

sff_exec()
{
	_cmd=$1
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" >"$tsel"
	set --
	while IFS= read -r _path; do
		set -- "$@" "$(printf "%s" "$_path" | tr '\035' '\n')"
	done <"$tsel"
	rm -f "$tsel"
	sffpipe_refresh

	case "$_cmd" in
	'ed') [ -z "$1" ] && return 0
		LC_ALL= exec $EDITOR "$@";;
	'sh') echo ""
		export Q='exit'
		command -v bash >/dev/null 2>&1 && _sh='bash' || _sh='sh'
		LC_ALL= exec $_sh -s "$@";;
	esac
}

sff_chmod_chown()
{
	printf "\nMode or User:Group (e.g., 644, a+x, u:g): "; read -r _x
	[ -z "$_x" ] && exit 0
	printf "Apply recursively? (y/n) [n]: "; read -r _x2
	case "$_x2" in [yY]) _x2='-R';; *) _x2='';; esac

	sffpipe_get_sel
	case "$_x" in
	*:*) LC_ALL= xargs -0 chown $_x2 $_x <"$sffpipe";;
	*) LC_ALL= xargs -0 chmod $_x2 $_x <"$sffpipe";;
	esac || return 1
	sffpipe_refresh
}

sff_find()
{
	printf "\nSearch pattern (with wildcards *, ?): "; read -r _x
	case "$_x" in
	'') exit 0;;
	*[[:upper:]]*|*'['?']'*) _opt='-name';;
	*) _opt='-iname';;
	esac
	printf "More options (optional): "; read -r _x2
	echo "Searching... (in $cwd)"
	{ printf "?"; find . $_x2 $_opt "$_x" -print0 2>/dev/null | tr '\n\0' '\035\n' \
		| sed -e 's|^\./*||' -e '/^[./]$/d' -e '/^\.\.$/d' -e '/^$/d' | tr '\n\035' '\0\n'; } >"$sffpipe"
}

sff_file_stat()
{
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" | while IFS= read -r _path; do
		echo ""
		_path=$(printf "%s" "$_path" | tr '\035' '\n')
		LC_ALL= stat -x "$_path" 2>/dev/null || LC_ALL= stat "$_path"
		file -bi "$_path"
		file -b "$_path"
	done | LC_ALL= less
}

sff_disk_usage()
{
	sffpipe_get_sel
	echo ""
	LC_ALL= xargs -0 du -shc <"$sffpipe" | sort -h
	echo ""
	df -h "$cwd"
	return 1
}

sff_undo()
{
	[ ! -s "$lastop" ] || [ "$(find "$lastop" -mmin +360)" ] && exit 0
	case "$(cat "$lastop")" in
	'new'|'copy'|'duplicate') sff_undo_new;;
	'move'|'rename') sff_undo_move;;
	esac
}

sff_redo()
{
	[ ! -s "$lastop" ] && exit 0
	case "$(cat "$lastop")" in
	'unnew') sff_do_new;;
	'uncopy') sff_do_paste 'copy';;
	'unmove') sff_do_paste 'move';;
	'unrename') sff_do_rename;;
	'unduplicate') sff_do_duplicate;;
	esac
}

sff_help()
{
	sed -n '/[#][?][>]/{s/^.*[#][?][>]//;p;}' "$0" | LC_ALL= less
}

run_pl()
{
	_plugin="${sffdir}/plugins/$1"
	[ ! -e "$_plugin" ] && _plugin="${0%/*}/plugins/$1"
	[ ! -e "$_plugin" ] && _plugin="/usr/local/lib/sff/plugins/$1"
	[ ! -e "$_plugin" ] && _plugin="/usr/lib/sff/plugins/$1"
	if [ ! -e "$_plugin" ]; then
		printf "\n%s: plugin not found\n" "$1"
		return 1
	else
		LC_ALL= exec "$_plugin" "$2"
	fi
}

# === custom functions ===


# === key bindings ===
case "$1" in                  #?> Extension functions:
'n') sff_new;;                #?>     n  Create new file (append '/' for dir)
'd') sff_delete;;             #?>     d  Delete
'y') sff_write_cbuf 'cp';;    #?>     y  Copy
'x') sff_write_cbuf 'mv';;    #?>     x  Cut
'v') sff_view_cbuf;;          #?>     v  View buffer
'V') sff_clear_cbuf;;         #?>     V  Clear buffer
'p') sff_paste;;              #?>     p  Paste
'r') sff_rename;;             #?>     r  Rename
'R') sff_rename 'p';;         #?>     R  Rename (show path)
'Y') sff_duplicate;;          #?>     Y  Duplicate
'e') sff_exec 'ed';;          #?>     e  Edit file
'm') sff_chmod_chown;;        #?>     m  Change permissions or owner
'f') sff_find;;               #?>     f  Advanced search via 'find'
'i') sff_file_stat;;          #?>     i  File status
'I') sff_disk_usage;;         #?>     I  Disk usage
';') sff_exec 'sh';;          #?>     ;  Shell
'u') sff_undo;;               #?>     u  Undo last operation
'U') sff_redo;;               #?>     U  Redo last operation
'/') sff_help;;               #?>     /  Show this help
                              #?> Plugins:
'o') run_pl 'sfopen' 'o';;    #?>     o  Open with
'F') run_pl 'fzf-find';;      #?>     F  Search via 'fzf'
'=') run_pl 'preview' 'sw';;  #?>     =  Toggle preview
'z') run_pl 'archive' 'e';;   #?>     z  Extract archive
'Z') run_pl 'archive' 'c';;   #?>     Z  Create archive
esac                          #?>
                              #?>Use Alt+<Key> or 'u'-<Key> to invoke
                              #?>Press 'q' to leave this page
