#!/bin/sh

# BSD 2-Clause License
#
# Copyright (c) 2024-2026 Shi Yanling
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

EDITOR=${EDITOR:-vi}
export LC_ALL=C
unset LESS
cwd=$(pwd)
uid=$(id -u)

sffpipe=$1
sffdir=${sffpipe%/*}
tmpdir=${TMPDIR:-/tmp}
[ ! -w "$tmpdir" ] && tmpdir=$sffdir

exbuf1="${sffdir}/.exec-buf1"
exbuf2="${sffdir}/.exec-buf2"
lastop="${sffdir}/.last-operation"
cpbuf="${sffdir}/.buf-copy"
mvbuf="${sffdir}/.buf-move"
[ -e "$mvbuf" ] && cmbuf=$mvbuf || cmbuf=$cpbuf
tsel="${tmpdir}/sff-tmpsel-$uid"
tbuf1="${tmpdir}/sff-tmpbuf1-$uid"
tbuf2="${tmpdir}/sff-tmpbuf2-$uid"

# === sff extension functions ===

sffpipe_clear_sel()
{
	[ -p "$sffpipe" ] && printf "." >"$sffpipe"
}

sffpipe_refresh()
{
	[ "$1" = '-c' ] && _x='.' || _x=''
	[ -p "$sffpipe" ] && printf "*%s" "$_x" >"$sffpipe"
}

sffpipe_sel_file()
{
	[ -p "$sffpipe" ] && printf "@%s\0" "$1" >"$sffpipe"
}

sffpipe_enter_dir()
{
	[ -p "$sffpipe" ] && printf ">%s\0" "$1" >"$sffpipe"
}

sffpipe_get_sel()
{
	[ -p "$sffpipe" ] && printf "%s" "$$" >"$sffpipe"
	sel=$sffpipe
}

sff_init_bufs()
{
	[ -e "$exbuf1" ] && [ -e "$exbuf2" ] && [ -e "$lastop" ] && [ -e "$cmbuf" ] && return 0
	touch -a "$exbuf1" "$exbuf2" "$lastop" "$cmbuf"
	chmod 600 "$exbuf1" "$exbuf2" "$lastop" "$cmbuf"
	[ "$uid" -eq 0 ] && chown $(ps -o uid= -p "$PPID") "$exbuf1" "$exbuf2" "$lastop" "$cmbuf"
}

sff_abort()
{
	rm -f "$tbuf1" "$tbuf2" "$@"
	exit 0
}

sff_pwd_perm()
{
	if [ ! -w "$cwd" ]; then
		printf "\n%s: Permission denied\n" "$cwd"
		printf "Press Enter to continue "; read -r _x
		exit 0
	fi
}

sff_new()
{
	sff_pwd_perm
	sff_init_bufs
	_tlist="${tmpdir}/sff-create-files-$uid"
	: >"$_tlist"

	while true; do
		LC_ALL= $EDITOR "$_tlist"
		[ -e "$_tlist" ] && sed -e 's|^/*||' -e 's|[ \t]*$||' -e '/^$/d' "$_tlist" >"$tbuf1"
		[ ! -s "$tbuf1" ] && sff_abort "$_tlist"

		sed 's|/.*$||' "$tbuf1" | sort -u >"$tbuf2"
		_existf=$(tr '\n' '\0' <"$tbuf2" | xargs -0 ls -1d -- 2>/dev/null | head -n 80)
		[ -z "$_existf" ] && break

		printf "\n%s\n" "$_existf"
		echo "^^^ file exists"
		printf "(e)dit list / (c)ancel [e]: "; read -r _x
		case "$_x" in [cC]) sff_abort "$_tlist";; esac
	done

	_pwd=$(printf '%s' "$cwd" | tr '\n' '\035' | sed 's/[\|&]/\\&/g')
	sed "s|^|$_pwd/|" "$tbuf2" | tr '\n\035' '\0\n' >"$exbuf2"
	sed -e '/\//!d' -e 's|/[^/]*$||' -e "s|^|$_pwd/|" "$tbuf1" | sort -u | tr '\n' '\0' >"$exbuf1"
	printf "\n" >>"$exbuf1"
	sed -e '/\/$/d' -e "s|^|$_pwd/|" "$tbuf1" | tr '\n' '\0' >>"$exbuf1"

	rm -f "$_tlist" "$tbuf1" "$tbuf2"
	sff_do_new
}

sff_do_new()
{
	printf "new" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr -d '\n' | tr '\035' '\n')"

	_err=''
	[ "$(head -c 1 "$exbuf1" | tr -d '\n')" ] \
	&& { head -n 1 "$exbuf1" | tr -d '\n' | tr '\035' '\n' | LC_ALL= xargs -0 mkdir -p || _err=1; }

	[ "$(tail -c 1 "$exbuf1" | tr -d '\n' | tr '\0' 'A')" ] \
	&& { tail -n +2 "$exbuf1" | tr '\035' '\n' | LC_ALL= xargs -0 touch || _err=1; }
	[ "$_err" ] && { printf "Press Enter to continue "; read -r _x; }
}

sff_undo_new()
{
	[ ! -s "$exbuf2" ] && exit 0
	_op=$(cat "$lastop")

	echo ""
	tr '\n\0' '\035\n' <"$exbuf2" | head -n 160
	echo "^^^" $(tr '\n\0' '\035\n' <"$exbuf2" | wc -l) "files will be deleted"
	printf "Undo %s? (y/n) [n]: " "$_op"; read -r _x
	case "$_x" in [yY]) :;; *) exit 0;; esac

	printf "un%s" "$_op" >"$lastop"
	sffpipe_refresh

	LC_ALL= xargs -0 rm -rf <"$exbuf2" \
	|| { printf "Press Enter to continue "; read -r _x; }
}

sff_write_cbuf()
{
	sff_init_bufs
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sel" >"$cmbuf"
	case "$1" in
	'cp') [ -e "$mvbuf" ] && mv -f "$mvbuf" "$cpbuf";;
	'mv') [ -e "$cpbuf" ] && mv -f "$cpbuf" "$mvbuf";;
	esac
	sffpipe_clear_sel
}

sff_view_cbuf()
{
	echo ""
	if [ -s "$cmbuf" ]; then
		cat "$cmbuf"
		printf "%s: %s file(s)\n" "${cmbuf##*-}" $(wc -l <"$cmbuf")
	else
		echo "Buffer is empty"
	fi
	printf "Press Enter to continue "; read -r _x
}

sff_clear_cbuf()
{
	: >"$cmbuf"
}

sff_paste()
{
	[ ! -s "$cmbuf" ] || [ "$(find "$cmbuf" -mmin +30)" ] && exit 0
	sff_pwd_perm

	_x=''
	_exf=$(sed 's|^.*/||' "$cmbuf" | tr '\n\035' '\0\n' \
		| xargs -0 sh -c 'for f; do [ -e "$f" ] && printf "%s\n" "$f"; done' _)
	if [ "$_exf" ]; then
		printf "\n%s\n" "$_exf"
		echo "^^^ files exist"
		printf "(s)kip all / (i)nteractive / (o)verwrite all / (c)ancel [c]: "; read -r _x
		case "$_x" in [sSiIoO]) :;; *) exit 0;; esac
	fi

	_pwd=$(printf "%s" "$cwd" | tr '\n' '\035' | sed 's/[\|&]/\\&/g')
	sed "G;s|$|$_pwd/|" "$cmbuf" | tr '\n\035' '\0\n' >"$exbuf1"

	_op=${cmbuf##*-}
	case "$_op" in
	'copy') sed "s|^.*/|$_pwd/|" "$cmbuf" | tr '\n\035' '\0\n' >"$exbuf2";;
	'move') sed "s|^.*/|$_pwd/|" "$cmbuf" | paste -d '\n' - "$cmbuf" | tr '\n\035' '\0\n' >"$exbuf2"
		: >"$cmbuf";;
	*) exit 0;;
	esac
	sff_do_paste "$_op" "${_x:-w}"
}

sff_do_paste()
{
	printf "%s" "$1" >"$lastop"
	[ "$2" != 'w' ] && touch -mt 202310011200.00 "$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr '\035' '\n')"

	unset LC_ALL
	case "$1" in
	'copy') printf "\nCopying...\n"
		case "$2" in
		[oOw]) xargs -0 -n 2 cp -afv <"$exbuf1";;
		[sS]) xargs -0 -n 2 cp -anv <"$exbuf1";;
		[iI]) xargs -0 -n 2 -o cp -aiv <"$exbuf1";;
		esac
		;;
	'move') printf "\nMoving...\n"
		case "$2" in
		[oOw]) xargs -0 -n 2 mv -fv <"$exbuf1";;
		[sS]) xargs -0 -n 2 mv -nv <"$exbuf1";;
		[iI]) xargs -0 -n 2 -o mv -iv <"$exbuf1";;
		esac
		;;
	esac || { printf "Press Enter to continue "; read -r _x; }
}

sff_rename()
{
	sff_init_bufs
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sel" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	sed 's|/[^/]*$||' "$tsel" >"$tbuf1"
	_tlist="${tmpdir}/sff-rename-$uid"
	if [ "$1" = 'p' ]; then
		cat "$tsel" >"$_tlist"
	else
		sed 's|.*/||' "$tsel" >"$_tlist"
	fi

	while true; do
		LC_ALL= $EDITOR "$_tlist"
		sed -e 's|.*/||' -e 's|^[ \t]*$||' "$_tlist" | paste -d '/' "$tsel" "$tbuf1" - \
		| sed -e '/^\(.*\)\1$/d' -e '/^/d' -e '/\/$/d' >"$tbuf2"
		[ ! -s "$tbuf2" ] && sff_abort "$_tlist"

		_dupn=$(cut -d '' -f 2 "$tbuf2" | sort | uniq -d)
		[ "$_dupn" ] && printf "\n%s\n^^^ duplicate names\n" "$_dupn"

		_exf=$(cut -d '' -f 2 "$tbuf2" | tr '\n\035' '\0\n' \
			| xargs -0 sh -c 'for f; do [ -e "$f" ] && printf "%s\n" "$f"; done' _)
		[ "$_exf" ] && printf "\n%s\n^^^ file exists\n" "$_exf"

		[ -z "$_dupn" ] && [ -z "$_exf" ] && break
		printf "(e)dit list / (c)ancel [e]: "; read -r _x
		case "$_x" in [cC]) sff_abort "$_tlist";; esac
	done

	tr '\036\n\035' '\0\0\n' <"$tbuf2" >"$exbuf1"
	sed 's/\(.*\)\(.*\)/\2\1/' "$tbuf2" | tr '\036\n\035' '\0\0\n' >"$exbuf2"
	rm -f "$_tlist" "$tbuf1" "$tbuf2"
	sff_do_rename
}

sff_do_rename()
{
	printf "rename" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr '\035' '\n')"

	printf "\nRenaming...\n"
	LC_ALL= xargs -0 -n 2 mv -nv <"$exbuf1" \
	|| { printf "Press Enter to continue "; read -r _x; }
}

sff_undo_move()
{
	[ ! -s "$exbuf2" ] && exit 0
	_op=$(cat "$lastop")
	echo ""
	xargs -0 -n 2 printf "%s -> %s\n" <"$exbuf2" | head -n 160
	printf "Undo %s? (y/n) [n]: " "$_op"; read -r _x
	case "$_x" in [yY]) :;; *) exit 0;; esac

	printf "un%s" "$_op" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf1" | head -n 1 | tr -d '\n' | tr '\035' '\n')"

	LC_ALL= xargs -0 -n 2 mv -n <"$exbuf2" \
	|| { printf "Press Enter to continue "; read -r _x; }
}

sff_duplicate()
{
	sff_init_bufs
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sel" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	printf "\nNumber of copies / (c)ancel [1]: "; read -r _x
	_x=$(printf "%s" "${_x:-'1'}" | tr -cd '0-9')
	_x=${_x#"${_x%%[!0]*}"}
	[ -z "$_x" ] && exit 0

	: >"$exbuf1"; : >"$exbuf2"
	while IFS= read -r _path; do
		_num=1
		_path=$(printf "%s" "$_path" | tr '\035' '\n')

		for _ in $(seq "$_x"); do
			_npath="${_path}_$_num"
			_i=$_num
			while [ -e "$_npath" ]; do
				_i=$((_i + 1))
				_npath="${_path}_$_i"
			done
			_num=$((_i + 1))

			printf "%s\0%s\0" "$_path" "$_npath" >>"$exbuf1"
			printf "%s\0" "$_npath" >>"$exbuf2"
		done
	done <"$tsel"

	[ ! -s "$exbuf1" ] && exit 0
	sff_do_duplicate
}

sff_do_duplicate()
{
	printf "duplicate" >"$lastop"
	sffpipe_sel_file "$(tr '\n\0' '\035\n' <"$exbuf2" | head -n 1 | tr -d '\n' | tr '\035' '\n')"

	echo "Duplicating..."
	LC_ALL= xargs -0 -n 2 cp -an <"$exbuf1" \
	|| { printf "Press Enter to continue "; read -r _x; }
}

sff_delete()
{
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sel" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	echo ""
	head -n 160 "$tsel"
	printf "Permanently delete %s files? (y/n) [n]: " $(wc -l <"$tsel"); read -r _x
	case "$_x" in [yY]) :;; *) exit 0;; esac
	sffpipe_refresh -c

	tr '\n\035' '\0\n' <"$tsel" | LC_ALL= xargs -0 rm -rf \
	|| { printf "Press Enter to continue "; read -r _x; }
}

sff_edit_file()
{
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sel" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	while IFS= read -r _path; do
		_path=$(printf "%s" "$_path" | tr '\035' '\n')
		set -- "$@" "$_path"
	done <"$tsel"

	sffpipe_refresh
	LC_ALL= exec $EDITOR "$@"
}

sff_chmod_chown()
{
	printf "\nMode or User:Group (e.g., 644, a+x, u:g): "; read -r _x
	[ -z "$_x" ] && exit 0
	printf "Apply recursively? (y/n) [n]: "; read -r _x2
	case "$_x2" in [yY]) _x2='-R';; *) _x2='';; esac

	sffpipe_get_sel
	case "$_x" in
	*:*) LC_ALL= xargs -0 chown $_x2 $_x <"$sel";;
	*) LC_ALL= xargs -0 chmod $_x2 $_x <"$sel";;
	esac || { printf "Press Enter to continue "; read -r _x; }
	sffpipe_refresh
}

sff_find()
{
	printf "\nSearch pattern (with wildcards *, ?): "; read -r _x
	case "$_x" in
	'') exit 0;;
	*[[:upper:]]*|*'['?']'*) _opt='-name';;
	*) _opt='-iname';;
	esac
	printf "More options (optional): "; read -r _x2
	echo "Searching... (in $cwd)"
	{ printf "?"; find . $_x2 $_opt "$_x" -print0 2>/dev/null | tr '\n\0' '\035\n' \
		| sed -e 's|^\./*||' -e '/^[./]$/d' -e '/^\.\.$/d' -e '/^$/d' | tr '\n\035' '\0\n'; } >"$sffpipe"
}

sff_file_stat()
{
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sel" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	while IFS= read -r _path; do
		echo ""
		_path=$(printf "%s" "$_path" | tr '\035' '\n')
		stat -x "$_path" 2>/dev/null || stat "$_path"
		file -bi "$_path"
		file -b "$_path"
	done <"$tsel"
	printf "Press Enter to continue "; read -r _x
}

sff_disk_usage()
{
	sffpipe_get_sel
	echo ""
	LC_ALL= xargs -0 du -shc <"$sel" | sort -h
	echo ""
	df -h "$cwd"
	printf "Press Enter to continue "; read -r _x
}

sff_undo()
{
	[ ! -s "$lastop" ] || [ "$(find "$lastop" -mmin +360)" ] && exit 0
	case "$(cat "$lastop")" in
	'new'|'copy'|'duplicate') sff_undo_new;;
	'move'|'rename') sff_undo_move;;
	esac
}

sff_redo()
{
	[ ! -s "$lastop" ] && exit 0
	case "$(cat "$lastop")" in
	'unnew') sff_do_new;;
	'uncopy') sff_do_paste 'copy' 'w';;
	'unmove') sff_do_paste 'move' 'w';;
	'unrename') sff_do_rename;;
	'unduplicate') sff_do_duplicate;;
	esac
}

sff_help()
{
	sed -n '/[#][?][>]/p' "$0" | sed 's/^.*[#][?][>]//' | less
}

run_pl()
{
	_plugin="${sffdir}/plugins/$1"
	[ ! -e "$_plugin" ] && _plugin="${0%/*}/plugins/$1"
	[ ! -e "$_plugin" ] && _plugin="/usr/local/lib/sff/plugins/$1"
	[ ! -e "$_plugin" ] && _plugin="/usr/lib/sff/plugins/$1"
	if [ ! -e "$_plugin" ]; then
		printf "\nPlugin '%s' not found\n" "$1"
		printf "Press Enter to continue "; read -r _x
	else
		unset LC_ALL
		exec "$_plugin" "$sffpipe" "$2"
	fi
}

# === custom functions ===


# === key bindings ===
case "$2" in                  #?> Extension functions:
'n') sff_new;;                #?>     n  Create new file (append '/' for dir)
'd') sff_delete;;             #?>     d  Delete
'y') sff_write_cbuf 'cp';;    #?>     y  Copy
'x') sff_write_cbuf 'mv';;    #?>     x  Cut
'v') sff_view_cbuf;;          #?>     v  View buffer
'V') sff_clear_cbuf;;         #?>     V  Clear buffer
'p') sff_paste;;              #?>     p  Paste
'r') sff_rename;;             #?>     r  Rename
'R') sff_rename 'p';;         #?>     R  Rename (show path)
'Y') sff_duplicate;;          #?>     Y  Duplicate
'e') sff_edit_file;;          #?>     e  Edit file
'm') sff_chmod_chown;;        #?>     m  Change permissions or owner
'f') sff_find;;               #?>     f  Advanced search via 'find'
'i') sff_file_stat;;          #?>     i  File status
'I') sff_disk_usage;;         #?>     I  Disk usage
'u') sff_undo;;               #?>     u  Undo last operation
'U') sff_redo;;               #?>     U  Redo last operation
'/') sff_help;;               #?>     /  Show this help
                              #?> Plugins:
'F') run_pl 'fzf-find';;      #?>     F  Search via 'fzf'
'=') run_pl 'preview' 'tui';; #?>     =  Toggle preview
'z') run_pl 'archive' 'e';;   #?>     z  Extract archive
'Z') run_pl 'archive' 'c';;   #?>     Z  Create archive
esac                          #?>
                              #?>Use Alt+<Key> or 'u'-<Key> to invoke
                              #?>Press 'q' to leave this page
