#!/bin/sh

# Description: Extract and create archives
#
# Supported creation:
#   gz, bz2, xz, tar (with gz, bz2, xz), zip, 7z
#
# Supported extraction:
#    ar, arj, bz2, cab, chm, cpio, cramfs, deb, dmg, gz, iso, lzh, lzma,
#    msi, nsis, qcow2, rpm, squashfs, tar (with gz, bz2, xz), wim, xar,
#    xz, zip, Z, 7z
#
# Dependencies:
#   - tar, gzip, bzip2, xz
#   - 7zip
#
# Usage:
#   Extracting archives:
#     You can select multiple archives for batch extraction or content preview.
#
#   Creating archives:
#     Enter a filename with extension (e.g., foo.tar.gz, foo.txz, foo.zip) to
#     archive and compress selected files together.
#
#     For tar-based formats:
#       Files will be archived using relative paths only if all selected files
#       are located within the current directory or its subdirectories;
#       otherwise, absolute paths will be used.
#
#     For zip or 7z formats:
#       The directory hierarchy of the selected files will be ignored, and all
#       files will be packed directly into the archive without preserving paths.
#
#     If you enter just .gz, .bz2, or .xz as the filename, each selected file will
#     be individually compressed in the specified format.
#
# Shell: POSIX compliant
#
# Author: Shi Yanling

export LC_ALL=C
unset LESS
command -v 7zz >/dev/null 2>&1 && _7z='7zz' || _7z='7z'

if [ "$2" ]; then
	sffpipe=$1
	sffdir=${sffpipe%/*}
	tmpdir=${TMPDIR:-/tmp}
	[ ! -w "$tmpdir" ] && tmpdir=$sffdir
	tsel=$(mktemp -u "${tmpdir}/sff-tsel-XXXXXX")
	tbuf1=$(mktemp -u "${tmpdir}/sff-tbuf1-XXXXXX")
fi

sffpipe_refresh()
{
	[ "$1" = '-c' ] && _x='.' || _x=''
	[ -p "$sffpipe" ] && printf "*%s" "$_x" >"$sffpipe"
}

sffpipe_sel_file()
{
	[ -p "$sffpipe" ] && printf "@%s" "$1" >"$sffpipe"
}

sffpipe_get_sel()
{
	[ -p "$sffpipe" ] && printf "%s" "$$" >"$sffpipe" \
	|| { printf "\n%s: invalid FIFO file\n" "$sffpipe"; exit 1; }
}

sff_cleanup()
{
	_ecode=$?
	[ "$tsel" ] && rm -f "$tsel" "$tbuf1"
	[ "$_ecode" -gt 0 ] && { printf "Press Enter to continue "; read -r _x; }
}
trap sff_cleanup EXIT HUP INT QUIT TERM

list_archive()
{
	for _path in "$@"; do
		_name=${_path##*/}
		echo "  -- $_name --"
		case "$(printf "%s" "$_name" | tr 'A-Z' 'a-z')" in
		*?.tar.?*|*?.t?*) LC_ALL= tar -tf "$_path" ;;
		*?.gz) LC_ALL= zcat "$_path";;
		*?.bz2) LC_ALL= bzcat "$_path";;
		*?.xz) LC_ALL= xzcat "$_path";;
		*?.?*) LC_ALL= $_7z l "$_path" | sed -n '/Date[[:space:]]*Time.*Name/,$p' | cut -c 54- ;;
		esac
		echo ""
	done
	true
}

extract_archive()
{
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" >"$tsel"
	[ ! -s "$tsel" ] && exit 0
	printf "\n(l)ist contents / (e)xtract / (c)ancel [c]: "; read -r _x

	_selfile=''
	while IFS= read -r _path <&3; do
		_path=$(printf "%s" "$_path" | tr '\035' '\n')
		_wdir=${_path%/*}
		_name=${_path##*/}
		_bname=${_name%.?*}
		_bname=${_bname%.tar}

		case "$_name" in
		*?.?*) [ -d "$_path" ] && continue;;
		*) continue;;
		esac

		case "$_x" in
		[eE]) if [ -e "${_wdir}/$_bname" ]; then
				printf "'%s' exists. Overwrite? (y/n) [n]: " "$_bname"; read -r _x2
				case "$_x2" in [yY]) :;; *) continue;; esac
			fi
	 		_tdir=$(mktemp -d "${_wdir}/tmp.XXXXXX")
			rm -rf "${_wdir}/$_bname"

			printf "Extracting $_name\n"
			case "$(printf "%s" "$_name" | tr 'A-Z' 'a-z')" in
			*?.tar.?*|*?.t?*) cd "$_tdir" && LC_ALL= tar -xf "$_path";;
			*?.gz) gunzip -k "$_path";;
			*?.bz2) bunzip2 -k "$_path";;
			*?.xz) unxz -k "$_path";;
			*?.?*) cd "$_tdir" && LC_ALL= $_7z x -aoa -bso0 "$_path";;
			esac && _selfile="$_bname" || { printf "Press Enter to continue "; read -r _x2; }

			_num=$(find "$_tdir"/ -mindepth 1 -maxdepth 1 ! -name . ! -name .. -print0 | tr '\n\0' '\035\n' | wc -l)
			if [ -d "${_tdir}/$_bname" ] && [ "$_num" -eq 1 ]; then
				mv "${_tdir}/$_bname" "$_wdir"/
			elif [ ! -e "${_wdir}/$_bname" ] && [ "$_num" -gt 0 ]; then
				mv "$_tdir" "${_wdir}/$_bname"
			fi
			[ -e "$_tdir" ] && rm -rf "$_tdir"
			;;

		[lL]) set -- "$@" "$_path"
			;;
		*) exit 0
			;;
		esac
	done 3<"$tsel"

	case "$_x" in
	[eE]) if [ "$_selfile" ]; then
			sffpipe_sel_file "$_selfile"
		else
			sffpipe_refresh
		fi;;
	[lL]) [ "$1" ] && list_archive "$@" | LC_ALL= less -R;;
	esac
}

create_archive()
{
	sffpipe_get_sel
	tr '\n\0' '\035\n' <"$sffpipe" >"$tsel"
	[ ! -s "$tsel" ] && exit 0

	while true; do
		printf "\nArchive name (include extension): "; read -r _name
		[ -z "$_name" ] && exit 0
		if [ -e "$_name" ]; then
			printf "'%s' exists. Overwrite? (y/n) [n]: " "$_name"; read -r _x
			case "$_x" in [yY]) break;; esac
		else
			break
		fi
	done

	_pwd=$(printf '%s' "$(pwd)" | tr '\n' '\035' | sed -e 's/[^^]/[&]/g' -e 's/\^/\\^/g')
	if [ "$(sed "/^$_pwd\//d" "$tsel")" ]; then
		tr '\n\035' '\0\n' <"$tsel" >"$tbuf1"
	else
		sed "s|^$_pwd/||" "$tsel" | tr '\n\035' '\0\n' >"$tbuf1"
	fi
	rm -f "$_name"
	sffpipe_sel_file "$_name"

	printf "Creating $_name\n"
	case "$(printf "%s" "$_name" | tr 'A-Z' 'a-z')" in
	*?.tar.?*|*?.t?*) LC_ALL= xargs -0 tar -caf "$_name" -- <"$tbuf1";;
	*.gz) xargs -0 gzip -fk -- <"$tbuf1";;
	*.bz2) xargs -0 bzip2 -fk -- <"$tbuf1";;
	*.xz) xargs -0 xz -fk -- <"$tbuf1";;
	*?.zip|*?.7z) LC_ALL= xargs -0 "$_7z" a -bso0 "$_name" -- <"$tbuf1";;
	*) echo "Failed: unsupported archive format"; false;;
	esac
}

case "$2" in
'') list_archive "$1";;
'e') extract_archive;;
'c') create_archive;;
esac
