#!/usr/bin/env sh

sffpipe="$1"

sffpipe_enter()
{
	printf ">%s\0" "$1" >"$sffpipe"
}

if ! fzf --version >/dev/null; then
	printf "Press Enter to continue "; read -r x
	exit 0
fi
path=$(fzf)
[ "$path" ] && sffpipe_enter "$path"
