#!/bin/sh

# Description: sff preview script
#
# Dependencies:
#
# Usage:
#   This script is executed for each preview. Its output is displayed in sff preview pane.
#   You can customize file types and their preview methods within the 'case' block.
#   NOTE: Do not use interactive commands to produce output.
#
# Shell: POSIX compliant
#
# Author: Shi Yanling

if [ "$2" = 'sw' ]; then
	sffpipe=$1
	[ -p "$sffpipe" ] && printf "#%s" "$0" >"$sffpipe"
	exit 0
fi

archivepl="${0%/*}/archive"
lines=$1 # preview pane height
cols=$2 # preview pane width
path=$SFF_PV_PATH
mime=$(file -bL --mime-type "$path")

case "$mime" in
text/*|application/json) echo ""
	head -n $lines "$path" | tr -d '\r' | expand -t 4
	;;

application/*-tar|application/*-compressed*|application/*[!+]zip*|application/zip|\
application/x-xz|application/vnd.rar|application/x-iso9660-image) "$archivepl" "$path"
	;;

inode/directory) _cou=$(find -L "$path" -mindepth 1 -maxdepth 1 -printf '.' 2>/dev/null | wc -c)
	printf "  -- directory -- (%s files)\n" $_cou
	if [ "$_cou" -gt 75000 ]; then
		LC_COLLATE=C ls -1fAp "$path" | head -n $lines
	elif [ "$_cou" -gt 15000 ]; then
		LC_COLLATE=C ls -1Ap "$path" | head -n $lines
	else
		ls -1Ap "$path" | head -n $lines
	fi
	;;

*) printf "  -- %s --\n" "$mime"
	;;
esac
